element:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: parking_lot_management_system
    username: root
    password: 123

baidu:
  apikey: cc4PzH0kttWqEfC6qxKbHaeY
  secret-key: EHTLtgXeGhRT4u88jWPRimx30OyPCZDB

redis:
  host: localhost
  port: 6379
  password: 123
  database: 10