server:
  port: 8080

baidu:
  apikey: ${baidu.apikey}
  secret-key: ${baidu.secret-key}

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${element.datasource.driver-class-name}
    url: jdbc:mysql://${element.datasource.host}:${element.datasource.port}/${element.datasource.database}?characterEncoding=utf-8&useSSL=false
    username: ${element.datasource.username}
    password: ${element.datasource.password}
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
      database: ${redis.database}
  mvc:
    static-path-pattern: /**

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #日志设置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



file:
  path: ${file.path1}

element:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: housemayer
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
